# Generated by Django 2.2.7 on 2019-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
